configure.ac: we need to check for vasprintf explicitly, after all
On MinGW:
```
checking for asprintf()... yes
checking for vasprintf... no
```
```
.libs
/dvbpsi.o: In function `dvbpsi_message':
C:\msys64\home\appveyor\libdvbpsi\src/dvbpsi.c:527: undefined reference to `vasprintf'
collect2.exe: error: ld returned 1 exit status

Makefile:726: recipe for target 'libdvbpsi.la' failed
make[2]: *** [libdvbpsi.la] Error 1
```

Signed-off-by: Michael Ira Krufky <mkrufky@linuxtv.org>